services:
  - type: web
    name: Event-Ticket-Booking-System
    env: node
    plan: starter
    region: oregon

    buildCommand: npm run build
    startCommand: npm start

    healthCheckPath: /api/health

    envVars:
      - key: NODE_ENV
        value: production

      - key: MONGODB_URI
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: JWT_EXPIRES_IN
        value: 24h

      - key: RESERVATION_DURATION_MINUTES
        value: 10